# Patterns defined in this file will be checked against every line of output (e.g. port scans and service scans)

[[pattern]]
description = 'Nmap script found a potential vulnerability. ({match})'
pattern = 'State: (?:(?:LIKELY\_?)?VULNERABLE)'

[[pattern]]
pattern = '(?i)unauthorized'

[[pattern]]
description = 'Hardware Address detected. ({match})'
pattern = 'MAC Address: .*'

[[pattern]]
description = 'Operating System. ({match})'
pattern = 'OS details: .*'

[[pattern]]
description = 'Operating System guess. ({match})'
pattern = 'Aggressive OS guesses: .*'

